version: "3.8"
services:
  gateway:
    build:
      context: ./gateway
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: ./server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/shareit

  database:
    image: postgres:15.1-alpine3.17
    container_name: database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
